src/cobra/apps/organization/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django import forms
from django.db import transaction, IntegrityError
from django.utils.translation import ugettext_lazy as _

from cobra.core.loading import get_model, get_class
from cobra.forms.fields import UserField

Organization = get_model('organization', 'Organization')
OrganizationMember = get_model('organization', 'OrganizationMember')
Team = get_model('team', 'Team')
AuditLogEntry = get_model('auditlog', 'AuditLogEntry')
OrganizationMemberType = get_class('organization.utils', 'OrganizationMemberType')
AuditLogEntryEvent = get_class('auditlog.utils', 'AuditLogEntryEvent')


class OrganizationCreateForm(forms.ModelForm):
    name = forms.CharField(label=_('Organization Name'), max_length=200,
        widget=forms.TextInput(attrs={'placeholder': _('My Company')}))

    class Meta:
        fields = ('name',)
        model = Organization


MEMBERSHIP_CHOICES = (
    (OrganizationMemberType.MEMBER, _('Member')),
    (OrganizationMemberType.ADMIN, _('Admin')),
    (OrganizationMemberType.OWNER, _('Owner')),
)

class OrganizationMemberEditForm(forms.ModelForm):
    type = forms.TypedChoiceField(label=_('Membership Type'), choices=(), coerce=int)
    has_global_access = forms.BooleanField(
        label=_('This member should have access to all teams within the organization.'),
        required=False,
    )
    teams = forms.ModelMultipleChoiceField(
        queryset=Team.objects.none(),
        widget=forms.CheckboxSelectMultiple(),
        required=False,
    )

    class Meta:
        fields = ('type', 'has_global_access', 'teams')
        model = OrganizationMember

    def __init__(self, authorizing_access, *args, **kwargs):
        super(OrganizationMemberEditForm, self).__init__(*args, **kwargs)

        self.fields['type'].choices = [
            m for m in MEMBERSHIP_CHOICES
            if m[0] >= authorizing_access
        ]
        self.fields['teams'].queryset = Team.objects.filter(
            organization=self.instance.organization,
        )

    def save(self, actor, organization, ip_address=None):
        if self.cleaned_data['has_global_access']:
            self.cleaned_data['teams'] = []

        om = super(OrganizationMemberEditForm, self).save()

        AuditLogEntry.objects.create(
            organization=organization,
            actor=actor,
            ip_address=ip_address,
            target_object=om.id,
            target_user=om.user,
            event=AuditLogEntryEvent.MEMBER_EDIT,
            data=om.get_audit_log_data(),
        )

        return om


class OrganizationMemberCreateForm(forms.ModelForm):
    user = UserField()

    class Meta:
        fields = ('user',)
        model = OrganizationMember

    def save(self, actor, organization, ip_address):
        om = super(OrganizationMemberCreateForm, self).save(commit=False)
        om.organization = organization
        om.type = OrganizationMemberType.MEMBER

        sid = transaction.savepoint(using='default')
        try:
            om.save()
        except IntegrityError:
            transaction.savepoint_rollback(sid, using='default')
            return OrganizationMember.objects.get(
                user=om.user,
                organization=organization,
            ), False
        transaction.savepoint_commit(sid, using='default')

        AuditLogEntry.objects.create(
            organization=organization,
            actor=actor,
            ip_address=ip_address,
            target_object=om.id,
            target_user=om.user,
            event=AuditLogEntryEvent.MEMBER_ADD,
            data=om.get_audit_log_data(),
        )

        return om, True


class OrganizationMemberInviteForm(forms.ModelForm):
    class Meta:
        fields = ('email',)
        model = OrganizationMember

    def save(self, actor, organization, ip_address):
        om = super(OrganizationMemberInviteForm, self).save(commit=False)
        om.organization = organization
        om.type = OrganizationMemberType.MEMBER

        try:
            existing = OrganizationMember.objects.get(
                organization=organization,
                user__email__iexact=om.email,
            )
        except OrganizationMember.DoesNotExist:
            pass
        else:
            return existing, False

        sid = transaction.savepoint(using='default')
        try:
            om.save()
        except IntegrityError:
            transaction.savepoint_rollback(sid, using='default')
            return OrganizationMember.objects.get(
                email__iexact=om.email,
                organization=organization,
            ), False
        transaction.savepoint_commit(sid, using='default')

        AuditLogEntry.objects.create(
            organization=organization,
            actor=actor,
            ip_address=ip_address,
            target_object=om.id,
            event=AuditLogEntryEvent.MEMBER_INVITE,
            data=om.get_audit_log_data(),
        )

        om.send_invite_email()

        return om, True

src/cobra/apps/home/__init__.py
default_app_config = 'cobra.apps.home.config.HomeConfig'

src/cobra/apps/home/app.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from cobra.core.application import Application
from cobra.core.loading import get_class


class HomeApplication(Application):
    name = 'home'

    home_view = get_class('home.views', 'HomeView')
    help_view = get_class('home.views', 'HelpView')

    def get_urls(self):
        urls = [
            url(r'^$', self.home_view.as_view(), name='home'),

            url(r'^help/$', login_required(self.help_view.as_view()), name='help'),
        ]
        return self.post_process_urls(urls)


application = HomeApplication()

src/cobra/apps/home/views.py
from __future__ import absolute_import
from braces.views import AnonymousRequiredMixin

from django.core.urlresolvers import reverse
from django.views.generic import TemplateView
from cobra.views.generic import OrganizationMixin


class HomeView(AnonymousRequiredMixin, OrganizationMixin, TemplateView):
    """
    This is the home page and will typically live at /
    """
    template_name = 'home/landing.html'

    def get_authenticated_redirect_url(self):
        # TODO(lyon): deal with case when the user cannot create orgs
        organization = self.get_active_organization(self.request)
        if organization is None:
            url = reverse('home:help')
        else:
            url = reverse('organization:home', args=[organization.slug])
        return url


class HelpView(TemplateView):
    template_name = 'home/help.html'

src/cobra/apps/organization/__init__.py
default_app_config = 'cobra.apps.organization.config.OrganizationConfig'

src/cobra/apps/organization/app.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from cobra.core.application import Application
from cobra.core.loading import get_class


class OrganizationApplication(Application):
    name = 'organization'
    organization_home_view = get_class('organization.views', 'OrganizationHomeView')
    organization_create_view = get_class('organization.views', 'OrganizationCreateView')
    organization_settings_view = get_class('organization.views', 'OrganizationSettingsView')
    organization_remove_view = get_class('organization.views', 'OrganizationRemoveView')

    organization_members_view = get_class('organization.views', 'OrganizationMembersView')
    organization_member_create_view = get_class('organization.views', 'OrganizationMemberCreateView')
    organization_member_settings_view = get_class('organization.views', 'OrganizationMemberSettingsView')
    organization_member_accept_view = get_class('organization.views', 'OrganizationMemberAcceptView')
    # organization_member_create_view = get_class('organization.views', 'OrganizationMemberCreateView')

    organization_my_list_view = get_class('organization.views', 'OrganizationMyListView')
    organization_all_list_view = get_class('organization.views', 'OrganizationAllListView')
    organization_join_view = get_class('organization.views', 'OrganizationJoinView')

    project_app = get_class('organization.project.app', 'application')

    workreport_app = get_class('organization.workreport.app', 'application')
    summary_app = get_class('organization.summary.app', 'application')

    # ajax
    organization_members_subordinates_view = get_class('organization.ajax', 'OrganizationMembersSubordinatesView')
    organization_search_suggestion_view = get_class('organization.ajax', 'OrganizationSearchSuggestionView')
    organization_departments_view = get_class('organization.ajax', 'OrganizationDepartmentsView')
    organization_department_view = get_class('organization.ajax', 'OrganizationDepartmentView')
    organization_department_delete_view = get_class('organization.ajax', 'OrganizationDepartmentDeleteView')
    organization_member_pinyin_indexs_view = get_class('organization.ajax', 'OrganizationMemberPinyinIndexsView')
    organization_member_list_view = get_class('organization.ajax', 'OrganizationMemberListView')
    organization_member_profile_view = get_class('organization.ajax', 'OrganizationMemberProfileView')

    def get_urls(self):
        urls = [
            url(r'^(?P<organization_slug>(?!create)[\w_-]+)/$', self.organization_home_view.as_view(),
                name='home'),

            url(r'^create/$', self.organization_create_view.as_view(),
                name='create'),

            url(r'^(?P<organization_slug>[\w_-]+)/settings/$', self.organization_settings_view.as_view(),
                name='settings'),
            url(r'^(?P<organization_slug>[\w_-]+)/remove/$', self.organization_remove_view.as_view(),
                name='remove'),

            url(r'^(?P<organization_slug>[\w_-]+)/members/$', self.organization_members_view.as_view(),
                name='members'),
            url(r'^(?P<organization_slug>[\w_-]+)/members/create/$', self.organization_member_create_view.as_view(),
                name='member-create'),
            url(r'^(?P<organization_slug>[\w_-]+)/members/(?P<member_id>\d+)/$', self.organization_member_settings_view.as_view(),
                name='member-settings'),

            url(r'^accept/(?P<member_id>\d+)/(?P<token>\w+)/$', self.organization_member_accept_view.as_view(),
                name='member-accept'),
            # url(r'^(?P<organization_slug>[\w_-]+)/members/new/$', self.organization_member_create_view.as_view(),
            #     name='member-create'),

            url(r'^(?P<organization_slug>[\w_-]+)/project/', include(self.project_app.urls)),
            url(r'^(?P<organization_slug>[\w_-]+)/workreport/', include(self.workreport_app.urls)),
            url(r'^(?P<organization_slug>[\w_-]+)/summary/', include(self.summary_app.urls)),

            url(r'^my/list/$', login_required(self.organization_my_list_view.as_view()),
                name='my-list'),
            url(r'^all/list/$', self.organization_all_list_view.as_view(),
                name='all-list'),

            url(r'^(?P<organization_slug>[\w_-]+)/join/$', self.organization_join_view.as_view(),
                name='join'),

            # ajax
            url(r'^(?P<organization_slug>[\w_-]+)/users/workreportSubordinates/(?P<user_id>\d+).json$', self.organization_members_subordinates_view.as_view(),
                name='ajax-members-subordinates'),
            url(r'^(?P<organization_slug>[\w_-]+)/search/suggestion.json$', self.organization_search_suggestion_view.as_view(),
                name='ajax-search-suggestion'),

            url(r'^(?P<organization_slug>[\w_-]+)/ajax/departments.json$', self.organization_departments_view.as_view(),
                name='ajax-departments'),
            url(r'^(?P<organization_slug>[\w_-]+)/ajax/department/(?P<department_id>\d+).json$', self.organization_department_view.as_view(),
                name='ajax-department'),
            url(r'^(?P<organization_slug>[\w_-]+)/ajax/department/delete.json$', self.organization_department_delete_view.as_view(),
                name='ajax-department-delete'),

            url(r'^(?P<organization_slug>[\w_-]+)/ajax/member/findPinyinIndexs.json$', self.organization_member_pinyin_indexs_view.as_view(),
                name='ajax-member-pinyin'),
            url(r'^(?P<organization_slug>[\w_-]+)/ajax/member/pageQuery.json$', self.organization_member_list_view.as_view(),
                name='ajax-member-list'),
            url(r'^(?P<organization_slug>[\w_-]+)/ajax/member/(?P<user_id>\d+).json$', self.organization_member_profile_view.as_view(),
                name='ajax-member-profile'),

        ]
        return self.post_process_urls(urls)


application = OrganizationApplication()

src/cobra/apps/organization/project/__init__.py
default_app_config = ('cobra.apps.organization.project.config.ProjectOrganizationConfig')

src/cobra/apps/organization/project/app.py
from django.conf.urls import url, include

from cobra.core.application import Application
from cobra.core.loading import get_class


class ProjectOrganizationApplication(Application):
    name = 'project'

    overview_view = get_class('organization.project.views', 'OverviewView')

    # workreport_app = get_class('organization.project.workreport.app', 'application')

    def get_urls(self):
        urls = [
            url(r'^(?P<project_slug>[\w_-]+)/overview/$', self.overview_view.as_view(), name='overview'),

            # url(r'^(?P<project_slug>[\w_-]+)/workreport/', include(self.workreport_app.urls)),
        ]
        return self.post_process_urls(urls)


application = ProjectOrganizationApplication()

src/cobra/apps/organization/project/views.py
from __future__ import absolute_import
from django.shortcuts import get_object_or_404
from cobra.apps.svnkit.utils.util import get_readme
from cobra.core.loading import get_model, get_class
from django.utils.translation import ugettext_lazy as _
from django.views import generic
from cobra.views.generic import ProjectView


Organization = get_model('organization', 'Organization')
Team = get_model('team', 'Team')
Project = get_model('project', 'Project')
Repository = get_model('svnkit', 'Repository')


class OverviewView(ProjectView):
    # template_name = 'organization/project/overview.html'
    def get(self, request, organization, team, project):
        self.project = project
        repository = self.get_repository()
        readme = get_readme(repository)

        context = {
            'active_nav': 'overview',
            'readme': readme
        }
        return self.respond('organization/project/overview.html', context)

    def get_repository(self):
        repository_lookup = {'project': self.project}
        repository = get_object_or_404(
            Repository, **repository_lookup)
        return repository

src/cobra/apps/organization/summary/__init__.py
default_app_config = ('cobra.apps.organization.summary.config.SummaryOrganizationConfig')

src/cobra/apps/organization/summary/app.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from cobra.core.application import Application
from cobra.core.loading import get_class


class SummaryOrganizationApplication(Application):
    name = 'summary'

    summary_report_view = get_class('organization.summary.views', 'SummaryReportView')

    # ajax
    ajax_view = get_class('organization.summary.ajax', 'AjaxView')
    ajax_workreport_view = get_class('organization.summary.ajax', 'AjaxWorkreportView')
    ajax_update_workreport_view = get_class('organization.summary.ajax', 'AjaxUpdateWorkreportView')

    def get_urls(self):
        urls = [
            url(r'^(?P<username>[\@\.\w-]+)/$', login_required(self.summary_report_view.as_view()), name='summary-member'),

            # ajax
            url(r'^ajax/view.json$', login_required(self.ajax_view.as_view()), name='ajax-summary-view'),
            url(r'^ajax/workreport.json$', login_required(self.ajax_workreport_view.as_view()), name='ajax-workreport-view'),
            url(r'^ajax/(?P<pk>[0-9]+).json$', login_required(self.ajax_update_workreport_view.as_view()), name='ajax-update-workreport-view'),

        ]
        return self.post_process_urls(urls)


application = SummaryOrganizationApplication()

src/cobra/apps/organization/summary/views.py
from __future__ import absolute_import
import calendar
from collections import OrderedDict
import collections
from itertools import groupby
import json
from braces.views import JSONResponseMixin
import datetime
from django import http
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.utils.dates import MONTHS
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.generic import View

from cobra.core.loading import get_model, get_class
from django.utils.translation import ugettext_lazy as _, ugettext
from django.views import generic
from cobra.views.generic import ProjectView, OrganizationView
from cobra.core.utils import date_from_string, get_datetime_now, get_local_datetime_now
from cobra.core.calendar import get_calendar_first_weekday
from cobra.core.compat import get_user_model
from cobra.core.render import render_to_string

User = get_user_model()


class SummaryReportView(OrganizationView):
    def get(self, request, organization, *args, **kwargs):
        summary_user = get_object_or_404(User, username__iexact=self.kwargs['username'])

        context = {
            'active_nav': 'summary_report',
        }
        template_name = 'organization/summary/summary_report.html'
        return self.respond(template_name, context)

src/cobra/templates/cobra/organization/all_organizations.html
{% extends "layouts/modal.html" %}
{% load i18n %}
{% load helper_tags organization_tags permissions_tags %}

{% block title %}
  {% trans 'All Organizations' %} | {{ block.super }}
{% endblock %}

{% block main %}
  {% if request.user.is_authenticated %}
    <ul class="nav nav-links">
      <li>
        <a href="{% url 'organization:my-list' %}">{% trans 'My organizations' %}</a>
      </li>
      <li class="active">
        <a href="{% url 'organization:all-list' %}">{% trans 'All organizations' %}</a>
      </li>
    </ul>
  {% endif %}
  <section class="body">
    <div class="row project-list">

    {% for organization in organizations %}
		<div class="project">
			<div class="info">
        <div class="name">
          {% if request.user.is_authenticated and request.user|can_visit_organization:organization %}
            <a href="{% url 'organization:home' organization.slug %}">{{ organization.name }}</a>
          {% else %}
            {{ organization.name }}
          {% endif %}
				</div>
				<div class="category">{% trans 'Owner is' %} {{ organization.owner|user_display_name }}</div>
				<div class="last-update">
					{% trans 'Created at' %} {{ organization.date_added|timesince_ago }}
				</div>
			</div>
			<div class="members">
        {% organization_members_with_filter organization limit=4 as organization_members %}
        {% for member in organization_members %}
            <img alt="{{ member.user|user_display_name }}" src="{% get_avatar_url member.user %}" title="{{ member.user|user_display_name }}">
        {% endfor %}
				
				<a href="#" class="add-more">
					<i class="fa fa-plus"></i>
				</a>
				<ul class="menu">
          {% if request.user.is_authenticated %}
            {% if request.user|can_visit_organization:organization %}
              {% if request.user|can_manage_org:organization %}
                <li><a href="{% url 'organization:member-create' organization.slug %}">{% trans 'Invite a new member' %}</a></li>
                <li><a href="{% url 'organization:settings' organization.slug %}">{% trans 'Change name' %}</a></li>
                <li><a href="{% url 'organization:settings' organization.slug %}#delete-org">{% trans 'Delete organization' %}</a></li>
              {% else %}
                <li><a href="{% url 'organization:home' organization.slug %}">{% trans 'Visit it' %}</a></li>
              {% endif %}
            {% else %}
              <li><a href="{% url 'organization:join' organization.slug %}">{% trans 'Join in' %}</a></li>
            {% endif %}
          {% else %}
            <li><a href="{% url 'organization:join' organization.slug %}">{% trans 'Join in' %}</a></li>
          {% endif %}
				</ul>
			</div>
		</div>
    {% endfor %}
		
	</div>
  </section>
{% endblock %}

{% block onbodyload %}
  {{ block.super }}

  new app.OrganizationPage();
{% endblock %}

src/cobra/templates/cobra/organization/create.html
{% extends "layouts/modal.html" %}

{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}{% trans "New Organization" %} | {{ block.super }}{% endblock %}

{% block main %}
  <section class="body">
    <div class="page-header">
      <h2>{% trans "Create a New Organization" %}</h2>
    </div>

    <p>{% blocktrans %}Organizations represent the top level in your hierarchy. You'll be able to bundle a collection of teams within an organization as well as give organization-wide permissions to users.{% endblocktrans %}</p>

    <br>

    <form class="form-stacked" action="" method="post">
      {% csrf_token %}
      {{ form|as_crispy_errors }}
      <div class="row">
        <div class="col-sm-6">
          <fieldset>
            {% for field in form %}
              {{ field|as_crispy_field }}
            {% endfor %}
          </fieldset>
        </div>
      </div>
      <fieldset class="form-actions">
          <button type="submit" class="btn btn-primary">{% trans "Create Organization" %}</button>
      </fieldset>
    </form>
  </section>
{% endblock %}

src/cobra/templates/cobra/organization/home.html
{% extends "layouts/organizationV2.html" %}

src/cobra/templates/cobra/organization/home_old.html
{% extends "layouts/organization.html" %}

{% load i18n %}

{% block org_teams_nav %}active{% endblock %}

{% block inner %}
  {% if not team_list %}
    <p>You don't have any teams for this organization yet. Get started by <a href="{% url 'team:create' organization.slug %}">creating your first team</a>.</p>
  {% else %}
    <ul class="team-list">
      {% for team, project_list in team_list %}
        <li>
          <h3>
            <div class="pull-right action-bar">
              <a href="{% url 'team:manage' team.slug organization.slug %}"><span class="icon-cog"></span>{% trans 'Team Settings' %}</a>
            </div>
            <a href="#">{{ team.name }}</a>
          </h3>
          {% if not project_list %}
            <p>There are no projects in this team. Would you like to <a href="{% url 'project:create' organization.slug %}?team={{ team.slug }}">create a project</a>?</p>
          {% else %}
            <ul>
              {% for project in project_list %}
                {% comment %}<li><a href="{% url 'svnkit:node' organization.slug project.slug '/' %}">{{ project.name }}</a></li>{% endcomment %}
                <li><a href="{% url 'organization:project:overview' organization.slug project.slug %}">{{ project.name }}</a></li>
              {% endfor %}
            </ul>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

src/cobra/templates/cobra/organization/member-accept-invite.html
{% extends "layouts/modal.html" %}

{% load i18n %}

{% block title %}{% trans "Member Invite" %} | {{ block.super }}{% endblock %}

{% block page_header_block %}{% endblock %}
{% block content_class %}{% endblock %}

{% block main %}
  <section class="body">
    <h2>{% trans "Join Organization" %}</h2><hr>
    
    <div class="row">
      <div class="col-sm-8">

        <p style="font-size: 1.3em;">
          {% blocktrans with org_name=organization.name %}<strong>{{ org_name }}</strong> is using Cobra to manage projects.{% endblocktrans %}
        </p>

        <p>{% blocktrans with project_count=project_list|length %}You can join to this organization, which manages <strong>{{ project_count }}</strong> project(s):{% endblocktrans %}</p>
        <ol class="p-l-20 m-b-10">
          {% for project in project_list|slice:"5" %}
            <li>
              {{ project.name }}
            </li>
          {% endfor %}
        </ol>

        {% if needs_authentication %}
          <p class="text-warning">{% trans "To continue, you must either login to your existing account, or create a new one." %}</p>

          <fieldset class="form-actions">
            <div class="pull-right" style="margin-top: 5px;">
              <a href="{% url 'account_login' %}">{% trans "Login as an existing user" %}</a>
            </div>
            <a href="{% url 'account_signup' %}" class="btn btn-primary">{% trans "Create a new account" %}</a>
          </fieldset>
        {% else %}
          <form method="POST">
            {% csrf_token %}
            <fieldset class="form-actions">
              <button type="submit" class="btn btn-primary">
                {% blocktrans with org_name=organization.name %}Join the {{ org_name }} organization{% endblocktrans %}
              </button>
            </fieldset>
          </form>
        {% endif %}
      </div>
    </div>
  </section>
{% endblock %}

src/cobra/templates/cobra/organization/member-create.html
{% extends "layouts/modal.html" %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load helper_tags %}

{% block title %}{% trans "Add Member to Organization" %} | {{ block.super }}{% endblock %}

{% block inner %}
  <div class="create-flow">
    <div class="page-header">
      <div class="pull-right">
        <a class="go-back"
           href="{% url 'organization:home' organization.slug %}">{% trans 'Back to Organization Home' %}</a>
      </div>
      <h2>{% trans "Add Member to Organization" %}</h2>
    </div>
    <hr>
    <div class="section">
      <h2 class="title">{% trans 'Through public invited link, quick!' %}</h2>

      <p class="desc">{% trans 'Send the public link to your colleague or partner through QQ or WeChart, visit the link to join your organization.We will Assign the user member authority' %}</p>

      <p class="join-link">{% url 'organization:join' organization.slug as join_url %}
        <input type="text" value="{{ join_url|absolute_url }}" class="clipboard-text" readonly="" style="color: #cf372b;">
      </p>

      <p class="caution">
        <em>{% trans 'Attention:' %} </em>
        {% trans 'Anyone who sees the invitation to link, can apply to join the team!' %}
      </p>
    </div>
    <hr>

    <fieldset>
      <h2 class="title">{% trans 'Invited through email' %}</h2>
      {% if is_invite %}
        <p>{% trans "Invite a member to join this organization via their email address. If they do not already have an account, they will first be asked to create one." %}</p>
        <p>{% trans "You will be able to configure permissions and team access on the following page." %}</p>
        {% trans "Send Invite" as submit_label %}
        {% include "partials/form.html" %}
      {% else %}
        <p>{% trans "You may add a user by their username if they already have an account." %}</p>
        <p>{% trans "You will be able to configure permissions and team access on the following page." %}</p>
        {% include "partials/form.html" %}
      {% endif %}
    </fieldset>
  </div>
{% endblock %}

src/cobra/templates/cobra/organization/member-settings.html
{% extends "layouts/modal.html" %}

{% load crispy_forms_tags %}
{% load i18n %}
{% load helper_tags %}

{% block title %}{% trans "Member Settings" %} | {{ block.super }}{% endblock %}

{% block inner %}
  <div class="page-header">
    <div class="pull-right">
      <a href="{% url 'organization:members' organization.slug %}">{% trans 'Back to Organization Members' %}</a>
    </div>
    <h2>
      {% trans 'Member Settings' %}
      <small>{{ member.get_display_name }}</small>
    </h2>
  </div>

  <form class="form-stacked" action="" method="post">
    {% csrf_token %}

    {% if form.errors %}
      <div class="alert alert-error">{% trans "Please correct the errors below." %}</div>
    {% endif %}

    {{ form|as_crispy_errors }}

    <fieldset>
      <div class="form-group">
        <label>{% trans "Email" %}</label>
        <a href="mailto:{{ member.get_email }}">{{ member.get_email }}</a>
      </div>

      <div class="form-group">
        <label>{% trans "Status" %}</label>
        {% if member.is_pending %}
          Invited
        {% else %}
          Active
        {% endif %}
      </div>
      <div class="row">
        <div class="col-sm-4">
          {{ form.type|as_crispy_field }}
        </div>
      </div>
    </fieldset>

    <fieldset>
      <h2>{% trans "Teams" %}</h2>

      {{ form.has_global_access|as_crispy_field }}

      <fieldset class="team-choices">
        {% for team_id, team_name in form.teams.field.choices %}
            <div class="checkbox">
              <label class="">
                <input type="checkbox" name="teams" value="{{ team_id }}"
                       class="checkboxinput"{% if team_id in form.teams.value %} checked="checked"{% endif %}>
                  {{ team_name }}
                </label>
            </div>
        {% endfor %}
      </fieldset>
    </fieldset>

    <div class="form-actions">
      <button type="submit" name="op" value="reinvite" class="btn btn-default">{% trans "Resend Invite" %}</button>
      <button type="submit" class="btn btn-primary">{% trans "Save Changes" %}</button>
    </div>
  </form>
{% endblock %}

{% block onbodyload %}
  {{ block.super }}
  var selector = $('.team-choices input[type=checkbox]');
  var selectedTeams = $('.team-choices input[type=checkbox]:checked').slice(0);
  $('#id_has_global_access').change(function(){
    var $this = $(this);
    var checked = $this.is(':checked');

    if (checked) {
      selectedTeams = $('.team-choices input[type=checkbox]:checked').slice(0);
      selector.prop('checked', true);
    } else {
      selector.prop('checked', false);
      $(selectedTeams).prop('checked', true);
      selectedTeams = [];
    }

    $('.team-choices').prop('disabled', checked);
  }).change();
{% endblock %}

src/cobra/templates/cobra/organization/members.html
{% extends "layouts/organizationV2.html" %}

{% load crispy_forms_tags %}
{% load i18n %}
{% load helper_tags %}

{% block title %}{% trans "Members" %} | {{ block.super }}{% endblock %}

{% block body_class %}{{ block.super }} org-members{% endblock %}
{% comment %}
{% block org_members_nav %}active{% endblock %}

{% block inner %}
  <div id="mainContainer">
    <div class="loading_cobra"></div>
  </div>
{% endblock %}

{% block onbodyload %}
  {{ block.super }}
{% endblock %}{% endcomment %}